#include "cmd-io/cmd-menu-content-table.h"
#include "util/int-char-converter.h"

const std::vector<menu_content> menu_info = {
    { _("持ち物", "Inventory"), 0 },
    { _("アイテム一覧", "Inventory list"), 'i' },
    { _("装備一覧", "Equipment list"), 'e' },
    { _("調査", "Observe an item"), 'I' },
    { _("落とす", "Drop an item"), 'd' },
    { _("壊す", "Destroy an item"), 'k' },
    { _("装備する", "Wear/wield equipment"), 'w' },
    { _("装備を外す", "Take off equipment"), 't' },
    { _("移動", "Movement"), 0 },
    { _("歩く", "Walk (with pickup)"), ';' },
    { _("歩く(拾わない)", "Walk (flip pickup)"), '-' },
    { _("走る", "Run"), '.' },
    { _("自動探索", "Auto-explore"), 'X' },
    { _("階段を上る", "Go up staircase"), '<' },
    { _("階段を下りる", "Go down staircase"), '>' },
    { _("トラベル", "Travel to a location"), '`' },
    { _("休息", "Resting"), 0 },
    { _("その場にとどまる", "Stay still (with pickup)"), ',' },
    { _("拾う", "Stay still (flip pickup)"), 'g' },
    { _("休息する", "Rest"), 'R' },
    { _("探す", "Search"), 's' },
    { _("探索モードのON/OFF", "Toggle search mode"), 'S' },
    { _("扉/箱", "Doors and walls"), 0 },
    { _("穴を掘る", "Tunnel"), 'T' },
    { _("開ける", "Open a door or chest"), 'o' },
    { _("閉じる", "Close a door"), 'c' },
    { _("くさびを打つ", "Jam a door"), 'j' },
    { _("体当たりする", "Bash a door"), 'B' },
    { _("トラップ解除", "Disarm a trap or chest"), 'D' },
    { _("何かをする", "Alter"), '+' },
    { _("魔法/特殊能力", "Magic and powers"), 0 },
    { _("調べる", "Browse magic list"), 'b' },
    { _("覚える", "Gain new spells"), 'G' },
    { _("使う", "Cast a spell / class power"), 'm' },
    { _("特殊能力を使う", "Use bonus power"), 'U' },
    { _("道具(使用)", "Objects"), 0 },
    { _("食べる", "Eat some food"), 'E' },
    { _("燃料を補給", "Fuel your lantern/torch"), 'F' },
    { _("飲む", "Quaff a potion"), 'q' },
    { _("読む", "Read a scroll"), 'r' },
    { _("銘を刻む", "Inscribe an object"), '{' },
    { _("銘を消す", "Uninscribe an object"), '}' },
    { _("始動する", "Activate equipped item"), 'A' },
    { _("魔法棒で狙う", "Aim a wand"), 'a' },
    { _("杖を使う", "Use a staff"), 'u' },
    { _("ロッドを振る", "Zap a rod"), 'z' },
    { _("射撃/投擲", "Throwing and firing"), 0 },
    { _("飛び道具で撃つ", "Fire an item"), 'f' },
    { _("投げる", "Throw an item"), 'v' },
    { _("ターゲット指定", "Targeting mode"), '*' },
    { _("見る", "Looking"), 0 },
    { _("ダンジョンの全体図", "Full screen map"), 'M' },
    { _("位置を確認", "Locate player on map"), 'L' },
    { _("周りを調べる", "Look around"), 'l' },
    { _("メッセージ", "Messages and notes"), 0 },
    { _("階の雰囲気", "Repeat level feeling"), KTRL('F') },
    { _("メッセージ履歴", "View previous messages"), KTRL('P') },
    { _("メモ", "Take notes"), ':' },
    { _("情報", "Game status"), 0 },
    { _("ステータス", "Character description"), 'C' },
    { _("現在の知識", "Check various information"), '~' },
    { _("プレイ記録", "Check play record"), '|' },
    { _("クエスト", "Quest status"), KTRL('Q') },
    { _("現在の時刻", "Display game time"), KTRL('T') },
    { _("セーブ/終了", "Saving and exiting"), 0 },
    { _("セーブ&中断", "Save and quit"), KTRL('X') },
    { _("セーブ", "Save"), KTRL('S') },
    { _("引退する", "Quit (commit suicide)"), 'Q' },
    { _("設定", "Options"), 0 },
    { _("オプション", "Interact with options"), '=' },
    { _("マクロ", "Interact with macros"), '@' },
    { _("画面表示", "Interact with visuals"), '%' },
    { _("カラー", "Interact with colors"), '&' },
    { _("設定変更コマンド", "Enter a user pref command"), '"' },
    { _("自動拾いをロード", "Reload auto-picker prefs"), '$' },
    { _("自動拾いを編集", "Edit auto-picker prefs"), '_' },
    { _("システム", "System"), '!' },
    { _("ヘルプ", "Help"), 0 },
    { _("ヘルプ", "Help"), '?' },
    { _("文字の説明", "Identify symbol"), '/' },
    { _("バージョン情報", "Game version"), 'V' },
    { _("その他", "Other"), 0 },
    { _("繰り返す", "Repeat last command"), 'n' },
    { _("ペットに命令する", "Command your pets"), 'p' },
    { _("持ち物/装備の切り替え", "Toggle choice window"), KTRL('I') },
    { _("再描画", "Redraw screen"), KTRL('R') },
    { _("記念撮影の表示", "Load screen dump"), '(' },
    { _("記念撮影", "Save screen dump"), ')' },
    { _("ランダムアーティファクト一覧", "List random artifacts"), KTRL('V') },
};
