#!/usr/bin/env python3
r"""Stand-ins for a 16x16 / 8x8 tile set of Hengband 3.x (one set each, never mixed).

Upstream lib/pref/graf-new.prf already maps R:<monrace id>, K:<baseitem id>,
F:<terrain id> to this sheet (ids checked against the "en" names of
lib/edit/*Definitions.jsonc: same name or a later rename).  Every id it
misses, or maps to a non-tile / empty cell, gets a stand-in from the same
set, written to lib/pref/graf-ab.prf (read at the end of graf-new.prf):
  monster: first mapped monster with the same symbol + colour, else symbol
  item:    same tval + symbol + colour, else same tval, else symbol
  terrain: its mimic's tile, else same symbol + colour, else symbol
  else (mimic monsters: `\ / ] 7`) an item/terrain of the same symbol;
  by hand: MUSEUM = BOOKSTORE's building, `N` (Shadower, joke N) = a `G`; UNDETECTED (unknown grid,
  upstream a text `x`) = an empty cell of the sheet (black).

Sets:
  python3 web/mkgraf-ab.py      Adam Bolt 16x16 (heng-graf-16x16.zip 16x16.bmp,
                                mask.bmp as alpha, web/tiles.webp): graf-new.prf -> graf-ab.prf
  python3 web/mkgraf-ab.py 8x8  Hengband's own 8x8 set (lib/xtra/graf/8x8.bmp,
                                multilockon123's update, opaque; web/tiles-8x8.webp):
                                graf-xxx.prf -> graf-8x8.prf (read after graf-xxx.prf,
                                graf-x11.prf).  Uniform (48,48,48) cells are unused."""
import re, sys
from PIL import Image
L = 'lib'
SET = (sys.argv[1:] or ['ab'])[0]
BASE, S = ('graf-xxx', 8) if SET == '8x8' else ('graf-new', 16)
img = Image.open('web/tiles-8x8.webp' if SET == '8x8' else 'web/tiles.webp').convert('RGBA')
W, H = img.size

def tile(a, c):
    x, y = (c & 0x7F) * S, (a & 0x7F) * S
    t = img.crop((x, y, x + S, y + S))
    return a & 0x80 and c & 0x80 and x + S <= W and y + S <= H and \
        t.getbbox() is not None and (SET != "8x8" or t.getcolors(1) != [(S * S, (48, 48, 48, 255))])

def load(f):
    txt = open(f'{L}/edit/{f}.jsonc', encoding='utf-8').read()
    parts = re.split(r'^      "id": (\d+),', txt, flags=re.M)
    d = {}
    for i in range(1, len(parts), 2):
        b, k = parts[i + 1], int(parts[i])
        if k == 0:
            continue
        g = lambda p: (re.search(p, b) or [None, None])[1]
        d[k] = dict(sym=(g(r'"character": "((?:\\.|[^"])*)"'), g(r'"color": "([^"]*)"')),
                    tval=g(r'"type_value": (\d+)'), key=g(r'"key": "([^"]*)"'),
                    mimic=g(r'"mimic": "([^"]*)"'))
    return d

J = {'R': load('MonraceDefinitions'), 'K': load('BaseitemDefinitions'), 'F': load('TerrainDefinitions')}
up = {}   # (kind, id) -> tail after "X:id:"
for line in open(f'{L}/pref/{BASE}.prf', encoding='latin-1'):
    m = re.match(r'([RKF]):(\d+):((0x\w+)[:/](0x\w+).*)', line.strip())
    if m and tile(int(m[4], 16), int(m[5], 16)):
        up[(m[1], int(m[2]))] = m[3]

def donor(kind, keyf, i):
    k = keyf(J[kind][i])
    for j in sorted(J[kind]):
        if (kind, j) in up and keyf(J[kind][j]) == k:
            return up[(kind, j)]

out, n = [], {'R': 0, 'K': 0, 'F': 0}
keys = {'F': {v['key']: k for k, v in J['F'].items()}}
for kind in 'RKF':
    for i in sorted(J[kind]):
        if (kind, i) in up:
            continue
        e = J[kind][i]
        t = None
        if kind == 'F' and e['mimic'] in keys['F']:
            t = up.get(('F', keys['F'][e['mimic']]))
        if kind == 'K':
            t = donor(kind, lambda v: (v['tval'], v['sym']), i) or donor(kind, lambda v: v['tval'], i)
        t = t or donor(kind, lambda v: v['sym'], i) or donor(kind, lambda v: v['sym'][0], i)
        if kind == 'F' and e['key'] == 'MUSEUM':
            t = up.get(('F', keys['F']['BOOKSTORE']))
        if kind == 'F' and e['key'] == 'UNDETECTED':
            t = up.get((kind, i)) or '0x83/0x8C'   # AB: an empty cell, the page draws black
        if kind == 'R' and e['sym'][0] == 'N':
            t = next(up[('R', j)] for j in sorted(J['R']) if ('R', j) in up and J['R'][j]['sym'][0] == 'G')
        for other in 'KFR':   # symbol only: J[other] ids differ, look up there
            t = t or next((up[(other, j)] for j in sorted(J[other])
                           if (other, j) in up and J[other][j]['sym'][0] == e['sym'][0]), None)
        if t:
            out.append(f'{kind}:{i}:{t}')
            n[kind] += 1
open(f'{L}/pref/graf-{SET}.prf', 'w').write(
    f'# File: graf-{SET}.prf\n# Stand-ins (same-set family tiles) for {"Hengband 8x8" if SET == "8x8" else "Adam Bolt 16x16"} where {BASE}.prf\n'
    f'# has none.  Generated by web/mkgraf-ab.py {SET}; do not edit.\n\n' + '\n'.join(out) + '\n')
print('stand-ins:', n, 'upstream tiles:', len(up))

if __name__ == '__main__':
    assert tile(0x80, 0x81) and not tile(0x01, 0x5E)   # a tile; text is not
