#!/usr/bin/env python3
r"""Stand-ins for Adam Bolt's 16x16 tiles (web/tiles.webp) in Hengband 3.x.

Upstream lib/pref/graf-new.prf already maps R:<monrace id>, K:<baseitem id>,
F:<terrain id> to this sheet (ids checked against the "en" names of
lib/edit/*Definitions.jsonc: same name or a later rename).  Every id it
misses, or maps to a non-tile / empty cell, gets a stand-in from the same
set, written to lib/pref/graf-ab.prf (read at the end of graf-new.prf):
  monster: first mapped monster with the same symbol + colour, else symbol
  item:    same tval + symbol + colour, else same tval, else symbol
  terrain: its mimic's tile, else same symbol + colour, else symbol
  else (mimic monsters: `\ / ] 7`) an item/terrain of the same symbol;
  by hand: MUSEUM = BOOKSTORE's building, `N` (Shadower, joke N) = a `G`; UNDETECTED (unknown grid,
  upstream a text `x`) = an empty cell of the sheet (black).

Sheet: Adam Bolt's 16x16 tiles (from FrogComposband lib/xtra/graf/16x16.bmp
+ mask.bmp, mask = alpha).  Run: python3 web/mkgraf-ab.py"""
import re
from PIL import Image
L = 'lib'
img = Image.open('web/tiles.webp').convert('RGBA')
W, H = img.size

def tile(a, c):
    x, y = (c & 0x7F) * 16, (a & 0x7F) * 16
    return a & 0x80 and c & 0x80 and x + 16 <= W and y + 16 <= H and \
        img.crop((x, y, x + 16, y + 16)).getbbox() is not None

def load(f):
    txt = open(f'{L}/edit/{f}.jsonc', encoding='utf-8').read()
    parts = re.split(r'^      "id": (\d+),', txt, flags=re.M)
    d = {}
    for i in range(1, len(parts), 2):
        b, k = parts[i + 1], int(parts[i])
        if k == 0:
            continue
        g = lambda p: (re.search(p, b) or [None, None])[1]
        d[k] = dict(sym=(g(r'"character": "((?:\\.|[^"])*)"'), g(r'"color": "([^"]*)"')),
                    tval=g(r'"type_value": (\d+)'), key=g(r'"key": "([^"]*)"'),
                    mimic=g(r'"mimic": "([^"]*)"'))
    return d

J = {'R': load('MonraceDefinitions'), 'K': load('BaseitemDefinitions'), 'F': load('TerrainDefinitions')}
up = {}   # (kind, id) -> tail after "X:id:"
for line in open(f'{L}/pref/graf-new.prf', encoding='latin-1'):
    m = re.match(r'([RKF]):(\d+):((0x\w+)/(0x\w+).*)', line.strip())
    if m and tile(int(m[4], 16), int(m[5], 16)):
        up[(m[1], int(m[2]))] = m[3]

def donor(kind, keyf, i):
    k = keyf(J[kind][i])
    for j in sorted(J[kind]):
        if (kind, j) in up and keyf(J[kind][j]) == k:
            return up[(kind, j)]

out, n = [], {'R': 0, 'K': 0, 'F': 0}
keys = {'F': {v['key']: k for k, v in J['F'].items()}}
for kind in 'RKF':
    for i in sorted(J[kind]):
        if (kind, i) in up:
            continue
        e = J[kind][i]
        t = None
        if kind == 'F' and e['mimic'] in keys['F']:
            t = up.get(('F', keys['F'][e['mimic']]))
        if kind == 'K':
            t = donor(kind, lambda v: (v['tval'], v['sym']), i) or donor(kind, lambda v: v['tval'], i)
        t = t or donor(kind, lambda v: v['sym'], i) or donor(kind, lambda v: v['sym'][0], i)
        if kind == 'F' and e['key'] == 'MUSEUM':
            t = up.get(('F', keys['F']['BOOKSTORE']))
        if kind == 'F' and e['key'] == 'UNDETECTED':
            t = '0x83/0x8C'   # empty cell: the page draws black
        if kind == 'R' and e['sym'][0] == 'N':
            t = next(up[('R', j)] for j in sorted(J['R']) if ('R', j) in up and J['R'][j]['sym'][0] == 'G')
        for other in 'KFR':   # symbol only: J[other] ids differ, look up there
            t = t or next((up[(other, j)] for j in sorted(J[other])
                           if (other, j) in up and J[other][j]['sym'][0] == e['sym'][0]), None)
        if t:
            out.append(f'{kind}:{i}:{t}')
            n[kind] += 1
open(f'{L}/pref/graf-ab.prf', 'w').write(
    '# File: graf-ab.prf\n# Stand-ins (same-set family tiles) for Adam Bolt 16x16 where graf-new.prf\n'
    '# has none.  Generated by web/mkgraf-ab.py; do not edit.\n\n' + '\n'.join(out) + '\n')
print('stand-ins:', n, 'upstream tiles:', len(up))

if __name__ == '__main__':
    assert tile(0x80, 0x81) and not tile(0x01, 0x5E)   # floor is a tile, text is not
